<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Exception Handling | Libelli</title>
<meta name=keywords content><meta name=description content="This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at Exception Handling. I&rsquo;m happy for any comments or pull requests on the notebook.
Exceptions
Exceptions are a tool that programmers use to describe errors or faults that are fatal to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their type - which describes broadly the class of exception that occurred, and by a message that says specifically what happened. Here are a few common exception types:"><meta name=author content="Benjamin Bengfort"><link rel=canonical href=https://bbengfort.github.io/2016/11/exception-handling/><link crossorigin=anonymous href=/assets/css/stylesheet.fc220c15db4aef0318bbf30adc45d33d4d7c88deff3238b23eb255afdc472ca6.css integrity="sha256-/CIMFdtK7wMYu/MK3EXTPU18iN7/MjiyPrJVr9xHLKY=" rel="preload stylesheet" as=style><link rel=icon href=https://bbengfort.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://bbengfort.github.io/icon.png><link rel=icon type=image/png sizes=32x32 href=https://bbengfort.github.io/icon.png><link rel=apple-touch-icon href=https://bbengfort.github.io/apple-touch-icon-precomposed.png><link rel=mask-icon href=https://bbengfort.github.io/icon.png><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=en href=https://bbengfort.github.io/2016/11/exception-handling/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><script async src="https://www.googletagmanager.com/gtag/js?id=G-D3BE7EHHVP"></script><script>var dnt,doNotTrack=!1;if(!1&&(dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes"),!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-D3BE7EHHVP")}</script><meta property="og:title" content="Exception Handling"><meta property="og:description" content="This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at Exception Handling. I&rsquo;m happy for any comments or pull requests on the notebook.
Exceptions
Exceptions are a tool that programmers use to describe errors or faults that are fatal to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their type - which describes broadly the class of exception that occurred, and by a message that says specifically what happened. Here are a few common exception types:"><meta property="og:type" content="article"><meta property="og:url" content="https://bbengfort.github.io/2016/11/exception-handling/"><meta property="og:image" content="https://bbengfort.github.io/bear.png"><meta property="article:section" content="posts"><meta property="article:published_time" content="2016-11-21T12:53:30+00:00"><meta property="article:modified_time" content="2016-11-21T12:53:30+00:00"><meta property="og:site_name" content="Libelli"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://bbengfort.github.io/bear.png"><meta name=twitter:title content="Exception Handling"><meta name=twitter:description content="This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at Exception Handling. I&rsquo;m happy for any comments or pull requests on the notebook.
Exceptions
Exceptions are a tool that programmers use to describe errors or faults that are fatal to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their type - which describes broadly the class of exception that occurred, and by a message that says specifically what happened. Here are a few common exception types:"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://bbengfort.github.io/posts/"},{"@type":"ListItem","position":2,"name":"Exception Handling","item":"https://bbengfort.github.io/2016/11/exception-handling/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Exception Handling","name":"Exception Handling","description":"This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at Exception Handling. I\u0026rsquo;m happy for any comments or pull requests on the notebook.\nExceptions Exceptions are a tool that programmers use to describe errors or faults that are fatal to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their type - which describes broadly the class of exception that occurred, and by a message that says specifically what happened. Here are a few common exception types:\n","keywords":[],"articleBody":"This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at Exception Handling. I’m happy for any comments or pull requests on the notebook.\nExceptions Exceptions are a tool that programmers use to describe errors or faults that are fatal to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their type - which describes broadly the class of exception that occurred, and by a message that says specifically what happened. Here are a few common exception types:\nSyntaxError: raised when the programmer has made a mistake typing Python code correctly. AttributeError: attempting to access an attribute on an object that does not exist KeyError: attempting to access a key in a dictionary that does not exist TypeError: raised when an argument to a function is not the right type (e.g. a str instead of int) ValueError: when an argument to a function is the right type but not in the right domain (e.g. an empty string) ImportError: raised when an import fails IOError: raised when Python cannot access a file correctly on disk Exceptions are defined in a class hierarchy - e.g. every exception is an object whose class defines it’s type. The base class is the Exception object. All Exception objects are initialized with a message - a string that describes exactly what went wrong. Constructed objects can then be “raised” or “thrown” with the raise keyword:\nraise Exception(\"Something bad happened!\") The reason the keyword is raise is because Python program execution creates what’s called a “stack” as functions call other functions, which call other functions, etc. When a function (at the bottom of the stack) raises an Exception, it is propagated up through the call stack so that every function gets a chance to “handle” the exception (more on that later). If the exception reaches the top of the stack, then the program terminates and a traceback is printed to the console. The traceback is meant to help developers identify what went wrong in their code.\nLet’s take a look at a simple example:\ndef main(badstep=None, **kwargs): \"\"\" This function is the entry point of the program, it does work on the arguments by calling each step function, which in turn call substep functions. Passing in a number for badstep will cause whichever step that is to raise an exception. \"\"\" step = 0 # count the steps # Execute each step one at a time. step = first(step, badstep) step = second(step, badstep) # Return a report return \"Sucessfully executed {} steps\".format(step) def first(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Call sub steps in order step = first_task_one(step, badstep) step = first_task_two(step, badstep) # Return the step that we're on return step def first_task_one(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Call sub steps in order step = first_task_one_subtask_one(step, badstep) # Return the step that we're on return step def first_task_one_subtask_one(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Return the step that we're on return step def first_task_two(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Return the step that we're on return step def second(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Call sub steps in order step = second_task_one(step, badstep) # Return the step that we're on return step def second_task_one(step, badstep=None): # Increment the step step += 1 # Check if this is a bad step if badstep == step: raise ValueError(\"Failed after {} steps\".format(step)) # Return the step that we're on return step The above example represents a fairly complex piece of code that has lots of functions that call lots of other functions. The question is then, how do we know where our code went wrong? The answer is the traceback - which deliniates exactly the functions that the exception was raised through. Let’s trigger the exception and the traceback:\nmain(3) --------------------------------------------------------------------------- ValueError Traceback (most recent call last) in () ----\u003e 1 main(3) in main(badstep, **kwargs) 12 13 # Execute each step one at a time. ---\u003e 14 step = first(step, badstep) 15 step = second(step, badstep) 16 in first(step, badstep) 28 29 # Call sub steps in order ---\u003e 30 step = first_task_one(step, badstep) 31 step = first_task_two(step, badstep) 32 in first_task_one(step, badstep) 44 45 # Call sub steps in order ---\u003e 46 step = first_task_one_subtask_one(step, badstep) 47 48 # Return the step that we're on in first_task_one_subtask_one(step, badstep) 56 # Check if this is a bad step 57 if badstep == step: ---\u003e 58 raise ValueError(\"Failed after {} steps\".format(step)) 59 60 # Return the step that we're on ValueError: Failed after 3 steps The way to read the traceback is to start at the very bottom. As you can see it indicates the type of the exception, followed by a colon, and then the message that was passed to the exception constructor. Often, this information is enough to figure out what is going wrong. However, if we’re unsure where the problem occurred, we can step back through the traceback in a bottom to top fashion.\nThe first part of the traceback indicates the exact line of code and file where the exception was raised, as well as the name of the function it was raised in. If you called main(3) than this indicates that first_task_one_subtask_one is the function where the problem occurred. If you wrote this function, then perhaps that is the place to change your code to handle the exception.\nHowever, many times you’re using third party libraries or Python standard library modules, meaning the location of the exception raised is not helpful, since you can’t change that code. Therefore, you will continue up the call stack until you discover a file/function in the code you wrote. This will provide the surrounding context for why the error was raised, and you can use pdb or even just print statements to debug the variables around that line of code. Alternatively you can simply handle the exception, which we’ll discuss shortly. In the example above, we can see that first_task_one_subtask_one was called by first_task_one at line 46, which was called by first at line 30, which was called by main at line 14.\nCatching Exceptions If the exception was caused by a programming error, the developer can simply change the code to make it correct. However, if the exception was created by bad user input or by a bad environmental condition (e.g. the wireless is down), then you don’t want to crash the program. Instead you want to provide feedback and allow the user to fix the problem or try again. Therefore in your code, you can catch exceptions at the place they occur using the following syntax:\ntry: # Code that may raise an exception except AttributeError as e: # Code to handle the exception case finally: # Code that must run even if there was an exception What we’re basically saying is try to do the code in the first block - hopefully it works. If it raises an AttributeError save that exception in a variable called e (the as e syntax) then we will deal with that exception in the except block. Then finally run the code in the finally block even if an exception occurs. By specifying exactly the type of exception we want to catch (AttributeError in this case), we will not catch all exceptions, only those that are of the type specified, including subclasses. If we want to catch all exceptions, you can use one of the following syntaxes:\ntry: # Code that may raise an exception except: # Except all exceptions or\ntry: # Code that may raise an exception except Exception as e: # Except all exceptions and capture in variable e However, it is best practice to capture only the type of exception you expect to happen, because you could accidentaly create the situation where you’re capturing fatal errors but not handling them appropriately. Here is an example:\nimport random class RandomError(Exception): \"\"\" A custom exception for this code block. \"\"\" pass def randomly_errors(p_error=0.5): if random.random() \u003c= p_error: raise RandomError(\"Error raised with {:0.2f} likelihood!\".format(p_error)) try: randomly_errors(0.5) print(\"No error occurred!\") except RandomError as e: print(e) finally: print(\"This runs no matter what!\") This code snippet demonstrates a couple of things. First you can define your own, program-specific exceptions by defining a class that extends Exception. We have done so and created our own RandomError exception class. Next we have a function that raises a RandomError with some likelihood which is an argument to the function. Then we have our exception handling block that calls the function and handles it.\nTry the following the code snippet:\nChange the likelihood of the error to see what happens except Exception instead of RandomError except TypeError instead of RandomError Call randomly_errors again inside of the except block Call randomly_errors again inside of the finally block Make sure you run the code multiple times since the error does occur randomly!\nLBYL vs. EAFP One quick note on exception handling in Python. You may wonder why you must use a try/except block to handle exceptions, couldn’t you simply do a check that the exception won’t occur before it does? For example, consider the following code:\nif key in mydict: val = mydict[key] # Do something with val else: # Handle the fact that mydict doesn't have a required key. This code checks if a key exists in the dictionary before using it, then uses an else block to handle the “exception”. This is an alternative to the following code:\ntry: val = mydict[key] # Do something with val except KeyError: # Handle the fact that mydict doesn't have a required key. Both blocks of code are valid. In fact they have names:\nLook Before You Leap (LBYL) Easier to Ask Forgiveness than Permission (EAFP) For a variety of reasons, the second example (EAFP) is more pythonic — that is the prefered Python Syntax, commonly accepted by Python developers. For more on this, please see Alex Martelli’s excellent PyCon 2016 talk, Exception and error handling in Python 2 and Python 3.\nContext Management Python does provide a syntax for embedding common try/except/finally blocks in an easy to read format called context management. To motivate the example, consider the following code snippet:\ntry: fobj = open('path/to/file.txt, 'r') data = fobj.read() except FileNotFoundError as e: print(e) print(\"Could not find the necessary file!) finally: fobj.close() This is a very common piece of code that opens a file and reads data from it. If the file doesn’t exist, we simply alert the user that the required file is missing. No matter what, the file is closed. This is critical because if the file is not closed properly, it can be corrupted or not available to other parts of the program. Data loss is not acceptable, so we need to ensure that no matter what the file is closed when we’re done with it. So we can do the following:\nwith open('path/to/file.txt', 'r') as fobj: data = fobj.read() The with as syntax implements context management. On with, a function called the enter function is called to do some work on behalf of the user (in this case open a file), and the return of that function is saved in the fobj variable. When this block is complete, the finally is called by implementing an exit function. (Note that the except part is not implemented in this particular code). In this way, we can ensure that the try/finally for opening and reading files is correctly implemented.\nWriting your own context managers is possible, but beyond the scope of this note (though I may write something on it shortly). Suffice it to say, you should always use the with/as syntax for opening files!\n","wordCount":"2105","inLanguage":"en","image":"https://bbengfort.github.io/bear.png","datePublished":"2016-11-21T12:53:30Z","dateModified":"2016-11-21T12:53:30Z","author":{"@type":"Person","name":"Benjamin Bengfort"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://bbengfort.github.io/2016/11/exception-handling/"},"publisher":{"@type":"Organization","name":"Libelli","logo":{"@type":"ImageObject","url":"https://bbengfort.github.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://bbengfort.github.io/ accesskey=h title="Libelli (Alt + H)"><img src=https://bbengfort.github.io/icon.png alt aria-label=logo height=35>Libelli</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://bbengfort.github.io/archive/ title=archive><span>archive</span></a></li><li><a href=https://bbengfort.github.io/categories/ title=categories><span>categories</span></a></li><li><a href=https://bbengfort.github.io/search/ title="search (Alt + /)" accesskey=/><span>search</span></a></li><li><a href=https://bbengfort.github.io/about/ title=about><span>about</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://bbengfort.github.io/>Home</a>&nbsp;»&nbsp;<a href=https://bbengfort.github.io/posts/>Posts</a></div><h1 class="post-title entry-hint-parent">Exception Handling</h1><div class=post-meta><span title='2016-11-21 12:53:30 +0000 UTC'>November 21, 2016</span>&nbsp;·&nbsp;10 min&nbsp;·&nbsp;2105 words&nbsp;·&nbsp;Benjamin Bengfort&nbsp;|&nbsp;<a href=https://github.com/bbengfort/bbengfort.github.io/tree/main/content/posts/2016-11-21-exception-handling.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=post-content><p>This short tutorial is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. These notes were originally created for a training I gave, and the notebook can be found at <a href=https://github.com/DistrictDataLabs/ceb-training/blob/master/notes/Exception%20Handling.ipynb>Exception Handling</a>. I&rsquo;m happy for any comments or pull requests on the notebook.</p><h2 id=exceptions>Exceptions<a hidden class=anchor aria-hidden=true href=#exceptions>#</a></h2><p><strong>Exceptions</strong> are a tool that programmers use to describe errors or faults that are <em>fatal</em> to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their <code>type</code> - which describes broadly the class of exception that occurred, and by a <code>message</code> that says specifically what happened. Here are a few common exception types:</p><ul><li><code>SyntaxError</code>: raised when the programmer has made a mistake typing Python code correctly.</li><li><code>AttributeError</code>: attempting to access an attribute on an object that does not exist</li><li><code>KeyError</code>: attempting to access a key in a dictionary that does not exist</li><li><code>TypeError</code>: raised when an argument to a function is not the right type (e.g. a <code>str</code> instead of <code>int</code>)</li><li><code>ValueError</code>: when an argument to a function is the right type but not in the right domain (e.g. an empty string)</li><li><code>ImportError</code>: raised when an import fails</li><li><code>IOError</code>: raised when Python cannot access a file correctly on disk</li></ul><p>Exceptions are defined in a class hierarchy - e.g. every exception is an object whose class defines it&rsquo;s type. The base class is the <code>Exception</code> object. All <code>Exception</code> objects are initialized with a message - a string that describes exactly what went wrong. Constructed objects can then be &ldquo;raised&rdquo; or &ldquo;thrown&rdquo; with the <code>raise</code> keyword:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>raise</span> <span class=ne>Exception</span><span class=p>(</span><span class=s2>&#34;Something bad happened!&#34;</span><span class=p>)</span>
</span></span></code></pre></div><p>The reason the keyword is <code>raise</code> is because Python program execution creates what&rsquo;s called a &ldquo;stack&rdquo; as functions call other functions, which call other functions, etc. When a function (at the bottom of the stack) raises an Exception, it is propagated up through the call stack so that every function gets a chance to &ldquo;handle&rdquo; the exception (more on that later). If the exception reaches the top of the stack, then the program terminates and a <em>traceback</em> is printed to the console. The traceback is meant to help developers identify what went wrong in their code.</p><p>Let&rsquo;s take a look at a simple example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>def</span> <span class=nf>main</span><span class=p>(</span><span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>,</span> <span class=o>**</span><span class=n>kwargs</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=s2>&#34;&#34;&#34;
</span></span></span><span class=line><span class=cl><span class=s2>    This function is the entry point of the program, it does
</span></span></span><span class=line><span class=cl><span class=s2>    work on the arguments by calling each step function, which
</span></span></span><span class=line><span class=cl><span class=s2>    in turn call substep functions.
</span></span></span><span class=line><span class=cl><span class=s2>
</span></span></span><span class=line><span class=cl><span class=s2>    Passing in a number for badstep will cause whichever step
</span></span></span><span class=line><span class=cl><span class=s2>    that is to raise an exception.
</span></span></span><span class=line><span class=cl><span class=s2>    &#34;&#34;&#34;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=mi>0</span> <span class=c1># count the steps</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Execute each step one at a time.</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>first</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>second</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return a report</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=s2>&#34;Sucessfully executed </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>)</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>first</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Call sub steps in order</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>first_task_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>first_task_two</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>first_task_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Call sub steps in order</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>first_task_one_subtask_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>first_task_one_subtask_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>first_task_two</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>second</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Call sub steps in order</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>=</span> <span class=n>second_task_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=p>)</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>second_task_one</span><span class=p>(</span><span class=n>step</span><span class=p>,</span> <span class=n>badstep</span><span class=o>=</span><span class=kc>None</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=c1># Increment the step</span>
</span></span><span class=line><span class=cl>    <span class=n>step</span> <span class=o>+=</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Check if this is a bad step</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>badstep</span> <span class=o>==</span> <span class=n>step</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=ne>ValueError</span><span class=p>(</span><span class=s2>&#34;Failed after </span><span class=si>{}</span><span class=s2> steps&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>step</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>    <span class=c1># Return the step that we&#39;re on</span>
</span></span><span class=line><span class=cl>    <span class=k>return</span> <span class=n>step</span>
</span></span></code></pre></div><p>The above example represents a fairly complex piece of code that has lots of functions that call lots of other functions. The question is then, <em>how do we know where our code went wrong?</em> The answer is the <em>traceback</em> - which deliniates exactly the functions that the exception was raised through. Let&rsquo;s trigger the exception and the traceback:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=n>main</span><span class=p>(</span><span class=mi>3</span><span class=p>)</span>
</span></span></code></pre></div><div class=highlight><pre tabindex=0 class=chroma><code class=language-text data-lang=text><span class=line><span class=cl>---------------------------------------------------------------------------
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>ValueError                                Traceback (most recent call last)
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>&lt;ipython-input-5-e46a77400742&gt; in &lt;module&gt;()
</span></span><span class=line><span class=cl>----&gt; 1 main(3)
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>&lt;ipython-input-4-03153844a5cc&gt; in main(badstep, **kwargs)
</span></span><span class=line><span class=cl>     12
</span></span><span class=line><span class=cl>     13     # Execute each step one at a time.
</span></span><span class=line><span class=cl>---&gt; 14     step = first(step, badstep)
</span></span><span class=line><span class=cl>     15     step = second(step, badstep)
</span></span><span class=line><span class=cl>     16
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>&lt;ipython-input-4-03153844a5cc&gt; in first(step, badstep)
</span></span><span class=line><span class=cl>     28
</span></span><span class=line><span class=cl>     29     # Call sub steps in order
</span></span><span class=line><span class=cl>---&gt; 30     step = first_task_one(step, badstep)
</span></span><span class=line><span class=cl>     31     step = first_task_two(step, badstep)
</span></span><span class=line><span class=cl>     32
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>&lt;ipython-input-4-03153844a5cc&gt; in first_task_one(step, badstep)
</span></span><span class=line><span class=cl>     44
</span></span><span class=line><span class=cl>     45     # Call sub steps in order
</span></span><span class=line><span class=cl>---&gt; 46     step = first_task_one_subtask_one(step, badstep)
</span></span><span class=line><span class=cl>     47
</span></span><span class=line><span class=cl>     48     # Return the step that we&#39;re on
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>&lt;ipython-input-4-03153844a5cc&gt; in first_task_one_subtask_one(step, badstep)
</span></span><span class=line><span class=cl>     56     # Check if this is a bad step
</span></span><span class=line><span class=cl>     57     if badstep == step:
</span></span><span class=line><span class=cl>---&gt; 58         raise ValueError(&#34;Failed after {} steps&#34;.format(step))
</span></span><span class=line><span class=cl>     59
</span></span><span class=line><span class=cl>     60     # Return the step that we&#39;re on
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>ValueError: Failed after 3 steps
</span></span></code></pre></div><p>The way to read the traceback is to start at the very bottom. As you can see it indicates the type of the exception, followed by a colon, and then the message that was passed to the exception constructor. Often, this information is enough to figure out what is going wrong. However, if we&rsquo;re unsure where the problem occurred, we can step back through the traceback in a bottom to top fashion.</p><p>The first part of the traceback indicates the exact line of code and file where the exception was raised, as well as the name of the function it was raised in. If you called <code>main(3)</code> than this indicates that <code>first_task_one_subtask_one</code> is the function where the problem occurred. If you wrote this function, then perhaps that is the place to change your code to handle the exception.</p><p>However, many times you&rsquo;re using third party libraries or Python standard library modules, meaning the location of the exception raised is not helpful, since you can&rsquo;t change that code. Therefore, you will continue up the call stack until you discover a file/function in the code you wrote. This will provide the surrounding context for why the error was raised, and you can use <code>pdb</code> or even just <code>print</code> statements to debug the variables around that line of code. Alternatively you can simply handle the exception, which we&rsquo;ll discuss shortly. In the example above, we can see that <code>first_task_one_subtask_one</code> was called by <code>first_task_one</code> at line 46, which was called by <code>first</code> at line 30, which was called by <code>main</code> at line 14.</p><h2 id=catching-exceptions>Catching Exceptions<a hidden class=anchor aria-hidden=true href=#catching-exceptions>#</a></h2><p>If the exception was caused by a programming error, the developer can simply change the code to make it correct. However, if the exception was created by bad user input or by a bad environmental condition (e.g. the wireless is down), then you don&rsquo;t want to crash the program. Instead you want to provide feedback and allow the user to fix the problem or try again. Therefore in your code, you can catch exceptions at the place they occur using the following syntax:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Code that may raise an exception</span>
</span></span><span class=line><span class=cl><span class=k>except</span> <span class=ne>AttributeError</span> <span class=k>as</span> <span class=n>e</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Code to handle the exception case</span>
</span></span><span class=line><span class=cl><span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Code that must run even if there was an exception</span>
</span></span></code></pre></div><p>What we&rsquo;re basically saying is <code>try</code> to do the code in the first block - hopefully it works. If it raises an <code>AttributeError</code> save that exception in a variable called <code>e</code> (the <code>as e</code> syntax) then we will deal with that exception in the <code>except</code> block. Then <code>finally</code> run the code in the <code>finally</code> block even if an exception occurs. By specifying exactly the type of exception we want to catch (<code>AttributeError</code> in this case), we will not catch all exceptions, only those that are of the type specified, including subclasses. If we want to catch <em>all</em> exceptions, you can use one of the following syntaxes:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Code that may raise an exception</span>
</span></span><span class=line><span class=cl><span class=k>except</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Except all exceptions</span>
</span></span></code></pre></div><p>or</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Code that may raise an exception</span>
</span></span><span class=line><span class=cl><span class=k>except</span> <span class=ne>Exception</span> <span class=k>as</span> <span class=n>e</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Except all exceptions and capture in variable e</span>
</span></span></code></pre></div><p>However, it is best practice to capture <em>only</em> the type of exception you expect to happen, because you could accidentaly create the situation where you&rsquo;re capturing fatal errors but not handling them appropriately. Here is an example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=kn>import</span> <span class=nn>random</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>class</span> <span class=nc>RandomError</span><span class=p>(</span><span class=ne>Exception</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=s2>&#34;&#34;&#34;
</span></span></span><span class=line><span class=cl><span class=s2>    A custom exception for this code block.
</span></span></span><span class=line><span class=cl><span class=s2>    &#34;&#34;&#34;</span>
</span></span><span class=line><span class=cl>    <span class=k>pass</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>def</span> <span class=nf>randomly_errors</span><span class=p>(</span><span class=n>p_error</span><span class=o>=</span><span class=mf>0.5</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=k>if</span> <span class=n>random</span><span class=o>.</span><span class=n>random</span><span class=p>()</span> <span class=o>&lt;=</span> <span class=n>p_error</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=k>raise</span> <span class=n>RandomError</span><span class=p>(</span><span class=s2>&#34;Error raised with </span><span class=si>{:0.2f}</span><span class=s2> likelihood!&#34;</span><span class=o>.</span><span class=n>format</span><span class=p>(</span><span class=n>p_error</span><span class=p>))</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>randomly_errors</span><span class=p>(</span><span class=mf>0.5</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;No error occurred!&#34;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=k>except</span> <span class=n>RandomError</span> <span class=k>as</span> <span class=n>e</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=n>e</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;This runs no matter what!&#34;</span><span class=p>)</span>
</span></span></code></pre></div><p>This code snippet demonstrates a couple of things. First you can define your own, program-specific exceptions by defining a class that extends <code>Exception</code>. We have done so and created our own <code>RandomError</code> exception class. Next we have a function that raises a <code>RandomError</code> with some likelihood which is an argument to the function. Then we have our exception handling block that calls the function and handles it.</p><p>Try the following the code snippet:</p><ul><li>Change the likelihood of the error to see what happens</li><li>except <code>Exception</code> instead of <code>RandomError</code></li><li>except <code>TypeError</code> instead of <code>RandomError</code></li><li>Call <code>randomly_errors</code> again inside of the <code>except</code> block</li><li>Call <code>randomly_errors</code> again inside of the <code>finally</code> block</li></ul><p>Make sure you run the code multiple times since the error does occur randomly!</p><h2 id=lbyl-vs-eafp>LBYL vs. EAFP<a hidden class=anchor aria-hidden=true href=#lbyl-vs-eafp>#</a></h2><p>One quick note on exception handling in Python. You may wonder why you must use a <code>try/except</code> block to handle exceptions, couldn&rsquo;t you simply do a check that the exception won&rsquo;t occur before it does? For example, consider the following code:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>if</span> <span class=n>key</span> <span class=ow>in</span> <span class=n>mydict</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>val</span> <span class=o>=</span> <span class=n>mydict</span><span class=p>[</span><span class=n>key</span><span class=p>]</span>
</span></span><span class=line><span class=cl>    <span class=c1># Do something with val</span>
</span></span><span class=line><span class=cl><span class=k>else</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Handle the fact that mydict doesn&#39;t have a required key.</span>
</span></span></code></pre></div><p>This code checks if a key exists in the dictionary before using it, then uses an else block to handle the &ldquo;exception&rdquo;. This is an alternative to the following code:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>val</span> <span class=o>=</span> <span class=n>mydict</span><span class=p>[</span><span class=n>key</span><span class=p>]</span>
</span></span><span class=line><span class=cl>    <span class=c1># Do something with val</span>
</span></span><span class=line><span class=cl><span class=k>except</span> <span class=ne>KeyError</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=c1># Handle the fact that mydict doesn&#39;t have a required key.</span>
</span></span></code></pre></div><p>Both blocks of code are valid. In fact they have names:</p><ol><li>Look Before You Leap (LBYL)</li><li>Easier to Ask Forgiveness than Permission (EAFP)</li></ol><p>For a variety of reasons, the second example (EAFP) is more <em>pythonic</em> — that is the prefered Python Syntax, commonly accepted by Python developers. For more on this, please see Alex Martelli&rsquo;s excellent PyCon 2016 talk, <a href="https://www.youtube.com/watch?v=frZrBgWHJdY">Exception and error handling in Python 2 and Python 3</a>.</p><h2 id=context-management>Context Management<a hidden class=anchor aria-hidden=true href=#context-management>#</a></h2><p>Python does provide a syntax for embedding common <code>try/except/finally</code> blocks in an easy to read format called context management. To motivate the example, consider the following code snippet:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>fobj</span> <span class=o>=</span> <span class=nb>open</span><span class=p>(</span><span class=s1>&#39;path/to/file.txt, &#39;</span><span class=sa>r</span><span class=s1>&#39;)</span>
</span></span><span class=line><span class=cl>    <span class=n>data</span> <span class=o>=</span> <span class=n>fobj</span><span class=o>.</span><span class=n>read</span><span class=p>()</span>
</span></span><span class=line><span class=cl><span class=k>except</span> <span class=ne>FileNotFoundError</span> <span class=k>as</span> <span class=n>e</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=n>e</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;Could not find the necessary file!)</span>
</span></span><span class=line><span class=cl><span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>fobj</span><span class=o>.</span><span class=n>close</span><span class=p>()</span>
</span></span></code></pre></div><p>This is a very common piece of code that opens a file and reads data from it. If the file doesn&rsquo;t exist, we simply alert the user that the required file is missing. No matter what, the file is closed. This is critical because if the file is not closed properly, it can be corrupted or not available to other parts of the program. Data loss is not acceptable, so we need to ensure that no matter what the file is closed when we&rsquo;re done with it. So we can do the following:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>with</span> <span class=nb>open</span><span class=p>(</span><span class=s1>&#39;path/to/file.txt&#39;</span><span class=p>,</span> <span class=s1>&#39;r&#39;</span><span class=p>)</span> <span class=k>as</span> <span class=n>fobj</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=n>data</span> <span class=o>=</span> <span class=n>fobj</span><span class=o>.</span><span class=n>read</span><span class=p>()</span>
</span></span></code></pre></div><p>The <code>with as</code> syntax implements context management. On <code>with</code>, a function called the <code>enter</code> function is called to do some work on behalf of the user (in this case open a file), and the return of that function is saved in the <code>fobj</code> variable. When this block is complete, the finally is called by implementing an <code>exit</code> function. (Note that the <code>except</code> part is not implemented in this particular code). In this way, we can ensure that the <code>try/finally</code> for opening and reading files is correctly implemented.</p><p>Writing your own context managers is possible, but beyond the scope of this note (though I may write something on it shortly). Suffice it to say, you should always use the <code>with/as</code> syntax for opening files!</p></div><footer class=post-footer><ul class=post-tags></ul><nav class=paginav><a class=prev href=https://bbengfort.github.io/2016/12/yielding-functions-for-iteration-golang/><span class=title>« Prev</span><br><span>Yielding Functions for Iteration in Go</span>
</a><a class=next href=https://bbengfort.github.io/2016/11/svg-timer-vertex/><span class=title>Next »</span><br><span>SVG Vertex with a Timer</span></a></nav></footer></article></main><footer class=footer><span>&copy; 2024 <a href=https://bbengfort.github.io/>Libelli</a></span> ·
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg>
</a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>